version: "3"
volumes:
  mysql_data:
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./logs:/var/log/nginx
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    build: ./php
    volumes:
      - ./code:/code
  mysql:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123

  