web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/code
    - ./logs:/var/log/nginx
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: ./php
  volumes:
    -  ./code:/code
mysql:
  image: mysql:5.6
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123
  volumes:
    -  ./mysql:/docker-entrypoint-initdb.d

  